using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace McpServer.Models;

public class SalesAnalytics
{
    [Required]
    [StringLength(50, MinimumLength = 1)]
    [Description("Time period for the sales analytics (e.g., 'Q1 2024', 'January 2024')")]
    public string Period { get; set; } = string.Empty;

    [Range(0, double.MaxValue)]
    [DisplayFormat(DataFormatString = "{0:C}")]
    [Description("Total revenue generated during the period")]
    public double TotalRevenue { get; set; }

    [Range(0, int.MaxValue)]
    [Description("Total number of orders placed during the period")]
    public int TotalOrders { get; set; }

    [Range(0, double.MaxValue)]
    [DisplayFormat(DataFormatString = "{0:C}")]
    [Description("Average value per order during the period")]
    public double AverageOrderValue { get; set; }

    [Range(0.0, 1.0)]
    [Description("Conversion rate as a decimal (0.0 to 1.0)")]
    public double ConversionRate { get; set; }

    [Description("List of top-selling products during the period")]
    public List<TopProduct> TopProducts { get; set; } = new List<TopProduct>();

    [Description("Sales data broken down by geographical region")]
    public List<RegionalSales> RegionalData { get; set; } = new List<RegionalSales>();

    [Required]
    [Description("Timestamp when this analytics report was generated")]
    public DateTime GeneratedAt { get; set; }
}

public class TopProduct
{
    [Required]
    [StringLength(100, MinimumLength = 1)]
    [Description("Name of the top-selling product")]
    public string Name { get; set; } = string.Empty;

    [Range(0, int.MaxValue)]
    [Description("Number of units sold")]
    public int Sales { get; set; }

    [Range(0, double.MaxValue)]
    [DisplayFormat(DataFormatString = "{0:C}")]
    [Description("Total revenue generated by this product")]
    public double Revenue { get; set; }
}

public class RegionalSales
{
    [Required]
    [StringLength(100, MinimumLength = 1)]
    [Description("Name of the geographical region")]
    public string Region { get; set; } = string.Empty;

    [Range(0, double.MaxValue)]
    [DisplayFormat(DataFormatString = "{0:C}")]
    [Description("Total revenue from this region")]
    public double Revenue { get; set; }

    [Range(0, int.MaxValue)]
    [Description("Number of orders from this region")]
    public int Orders { get; set; }
}
